-- Migration: cập nhật OrderStatus sang quy trình mua hàng Trung-Việt

CREATE TYPE "OrderStatus_new" AS ENUM (
  'CANCELLED',
  'DEPOSIT_PAID',
  'PURCHASED',
  'SHOP_SHIPPED',
  'IN_TRANSIT_TO_VN',
  'AT_VN_WAREHOUSE',
  'PAID',
  'COMPLETED',
  'COMPLAINT',
  'DELIVERY_REQUESTED'
);

ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "orders" ALTER COLUMN "status" TYPE "OrderStatus_new" USING (
  CASE "status"::text
    WHEN 'PENDING' THEN 'DEPOSIT_PAID'
    WHEN 'CONFIRMED' THEN 'DEPOSIT_PAID'
    WHEN 'PICKING_UP' THEN 'SHOP_SHIPPED'
    WHEN 'IN_TRANSIT' THEN 'IN_TRANSIT_TO_VN'
    WHEN 'DELIVERED' THEN 'COMPLETED'
    WHEN 'FAILED' THEN 'COMPLAINT'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    WHEN 'RETURNED' THEN 'COMPLAINT'
    ELSE 'DEPOSIT_PAID'
  END
)::"OrderStatus_new";

ALTER TABLE "order_events" ALTER COLUMN "status" TYPE "OrderStatus_new" USING (
  CASE "status"::text
    WHEN 'PENDING' THEN 'DEPOSIT_PAID'
    WHEN 'CONFIRMED' THEN 'DEPOSIT_PAID'
    WHEN 'PICKING_UP' THEN 'SHOP_SHIPPED'
    WHEN 'IN_TRANSIT' THEN 'IN_TRANSIT_TO_VN'
    WHEN 'DELIVERED' THEN 'COMPLETED'
    WHEN 'FAILED' THEN 'COMPLAINT'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    WHEN 'RETURNED' THEN 'COMPLAINT'
    ELSE 'DEPOSIT_PAID'
  END
)::"OrderStatus_new";

ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'DEPOSIT_PAID';

DROP TYPE "OrderStatus";
ALTER TYPE "OrderStatus_new" RENAME TO "OrderStatus";
